# Generated by Django 2.2.1 on 2019-05-11 09:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import osmcal.models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kind', models.CharField(choices=[(osmcal.models.EventType('Social'), 'Social'), (osmcal.models.EventType('Meeting'), 'Meeting'), (osmcal.models.EventType('Work'), 'Work'), (osmcal.models.EventType('Map Event'), 'Map Event'), (osmcal.models.EventType('Conference'), 'Conference')], max_length=4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end'], name='osmcal_even_end_4d0a53_idx'),
        ),
    ]
