# Generated by Django 2.2.1 on 2019-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0002_auto_20190511_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='whole_day',
            field=models.BooleanField(default=False),
        ),
    ]
