# Generated by Django 2.2.1 on 2019-05-12 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0003_auto_20190511_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('SOCI', 'Social'), ('MEET', 'Meeting'), ('WORK', 'Work'), ('MAPE', 'Map Event'), ('CONF', 'Conference')], max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
