# Generated by Django 2.2.3 on 2019-07-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0006_auto_20190731_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
