# Generated by Django 2.2.6 on 2019-10-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0009_eventparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation', to='osmcal.Event'),
        ),
    ]
