# Generated by Django 3.0.2 on 2020-02-01 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0013_remove_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Tell people what the event is about and what they can expect. You may use Markdown in this field.', null=True),
        ),
        migrations.CreateModel(
            name='ParticipationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_type', models.CharField(choices=[('TEXT', 'Text Field'), ('CHOI', 'Choice'), ('BOOL', 'Boolean')], max_length=4)),
                ('mandatory', models.BooleanField(default=True)),
                ('quota', models.PositiveIntegerField(blank=True, null=True)),
                ('choices', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='osmcal.Event')),
            ],
        ),
    ]
