# Generated by Django 3.0.2 on 2020-02-15 17:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0014_auto_20200201_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationquestion',
            name='quota',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
