# Generated by Django 3.0.2 on 2020-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0018_auto_20200221_1810'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participationanswer',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_question_answer'),
        ),
    ]
