# Generated by Django 3.0.2 on 2020-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0019_auto_20200222_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='added_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
