# Generated by Django 3.0.4 on 2020-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0021_auto_20200223_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
