# Generated by Django 3.1.1 on 2020-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0024_auto_20200516_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
