# Generated by Django 3.0.6 on 2020-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0025_auto_20200917_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('SOCI', 'Social'), ('MEET', 'Meeting'), ('WORK', 'Work'), ('MAPE', 'Map Event'), ('CONF', 'Conference')], max_length=4, null=True),
        ),
    ]
