# Generated by Django 3.1.1 on 2020-12-03 14:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0027_timezone_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
