# Generated by Django 3.2.12 on 2022-03-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0029_alter_event_description'),
    ]

    operations = [
        # This deletes already existing duplicates in the DB:
        migrations.RunSQL("""
            DELETE FROM osmcal_eventparticipation WHERE id IN ( 
                SELECT
                    p.id
                    FROM
                        (SELECT MIN(id) AS min_id, event_id, user_id FROM osmcal_eventparticipation GROUP BY(user_id, event_id)
                            HAVING COUNT(*) > 1) s,
                        osmcal_eventparticipation p
                    WHERE
                        p.event_id = s.event_id AND
                        p.user_id = s.user_id AND
                        p.id != s.min_id
                    ORDER BY p.added_on
            )"""),
        
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('event', 'user')},
        ),
    ]
