# Generated by Django 3.2.18 on 2023-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0031_event_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
