# Generated by Django 3.2.25 on 2025-02-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0032_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
