# Generated by Django 3.0.6 on 2020-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Community Name'),
        ),
    ]
