# Generated by Django 3.1.1 on 2020-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmcal', '0026_auto_20200524_1312'),
        ('community', '0002_auto_20200524_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='events',
            field=models.ManyToManyField(related_name='communities', to='osmcal.Event'),
        ),
    ]
